### ISSUE TITLE
docker-compose.yaml: bad bind mounts

### ISSUE THREAD

**Issue by Dope25** [Danixu/project-zomboid-server-docker#3]
Hi, I'm struggling with the docker bind mount.

Existing volume mounts in docker-compose.yaml point to the following directory for server data:
/home/steam/Zomboid 

However, inside that folder is only the workshop folder.
The actual server data (in the container) seems to be in the following directory:
/home/steam/pz-dedicated/ 

Any attempt at modifying the volume mount inside the docker-compose.yaml file results in a weird and seemingly unrelated error:

![image](https://user-images.githubusercontent.com/68992186/150013073-3ce8eaaf-57be-4564-97e9-fba943c7e724.png)

I've even tried adding an additional bind mount so as to not replace the default and I still get greeted with the same error.

Please help.

**Comment by Danixu** [comment]
Hello,

The server files required to run the server are stored in /home/steam/pz-dedicated/ like you are saying, but Save Data folder where the current state is stored, is in the Zomboid folder of the user that is running the server (unless you change it with the CACHEDIR environment variable).This container runs the server using the steam user and that is why I am binding the /home/steam/Zomboid folder.
If you bind the /home/steam/pz-dedicated/ then it is replaced with the external folder, so no server files will be available to run and that is why you get the error when it tries to run the start-server.sh file.

I am using this docker-compose file on my Fedora 35 with those binded folders for testing purposes, and is working perfectly. Also I am this image with the same binds on a Qnap NAS (which is based in Ubuntu), and data is preserved upon restarts, so I recommend you to keep the default binded folders.

Also check if the folder permissions are correct, because maybe git has not kept the same permissions that I have in my computer. Execute `chmod 775 data workshop-mods` and try it again.

Best regards.

**Comment by Dope25** [comment]
Thank you for the reply.
I'll look into it again with defaults.
After installing the container my next step was to look for configuration so when it didn't appear in data I couldn't really proceed.

Since data points to save and not to server config, I tried adding a third bind mount without altering the default ones and it still breaks the code.

As far as I understand, it should be completely transparent to the container so that where and what I mount from the container shouldn't matter to its operation at all. In that, changing the mounts shouldn't break the container's structure. 

Thanks

**Comment by Danixu** [comment]
Hello,

The data folder should have files once the server is started at least once. For example, this is the one I am using for testing:

```
$ du -hs *
12M	data
4,0K	docker-compose.yml
4,0K	Dockerfile
36K	LICENSE
8,0K	README.MD
16K	scripts
94M	workshop-mods
```

Those files includes the Single player data (which in server mode is not important), the MP Saves, and the server configuration:

```
[data]$ du -hs *
44K	db
2,9M	Logs
28K	messaging
4,0K	options.ini
8,0M	Saves
20K	Server
232K	server-console.txt
28K	Statistic
4,0K	Workshop
```

options.ini is the server global options like for example, and inside the Server foler you can see the files related to the Server configuration.

What folder do you mean (to investigate), because is the first server I have created and I have not found any additional folder in documentation yet, and maybe there are more files to backup. For now the private server I am hosting has no loose anything after several reboots. Even the Workshop mods folder is optional because the server downloads every mod at startup if doesn't exists, but I have prefered to keep it binded to boost the startup process when there are a lot of mods installed.

Best regards.

**Comment by Dope25** [comment]
I'm completely failing to get it to boot with default configuration currently (changed only the server name and admin password in .env).
Nothing gets written to data or workshop-mods, either.

After extracting the logs, it seems that the container is failing to write a few files:

ProjectZomboidDedicatedServer_1  | ERROR: General     , 1642623190104> 95,582,659> java.io.FileNotFoundException: /home/steam/Zomboid/Logs/19-01-22_20-13-10_DebugLog-server.txt (No such file or directory)


ProjectZomboidDedicatedServer_1  | LOG  : General     , 1642623190334> 95,582,888> creating server spawnregions file "/home/steam/Zomboid/Server/Raven_spawnregions.lua"
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1642623190335> 95,582,889> java.io.IOException: No such file or directory

ProjectZomboidDedicatedServer_1  | LOG  : General     , 1642623190345> 95,582,900> writing /home/steam/Zomboid/Server/Raven.ini
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1642623190350> 95,582,905> java.io.FileNotFoundException: /home/steam/Zomboid/Server/Raven.ini (No such file or directory)

ProjectZomboidDedicatedServer_1  | LOG  : General     , 1642623191832> 95,584,386> user database "/home/steam/Zomboid/db/Raven.db"
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1642623191833> 95,584,388> java.io.IOException: No such file or directory
ultimately failing in:

ProjectZomboidDedicatedServer_1  | LOG  : General     , 1642623191836> 95,584,390> failed to create user database, server shut down


Full logs attached.
[log.txt](https://github.com/Danixu/project-zomboid-server-docker/files/7900313/log.txt)



I saw you previously ask about the OS, this is Debian 11.

**Comment by Danixu** [comment]
Hello,

Try to chmod the data and workshop-mods, because the logs shows an error saying that is not able to write into the folder:

```
chmod 777 data workshop-mods
```

Best regards

**Comment by Dope25** [comment]
This worked. Thank you.

Finally the directories have appeared.
It's so weird that previously it would only show workshop within data.

Closing now!
